ALTER TABLE files DROP COLUMN source_url;
ALTER TABLE files ADD COLUMN storage_path TEXT NOT NULL DEFAULT '';
ALTER TABLE files ALTER COLUMN storage_path DROP DEFAULT;
ALTER TABLE files ALTER COLUMN size SET NOT NULL;
ALTER TABLE files ALTER COLUMN sha256 SET NOT NULL;
