[package]
name = "malprobe-database"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
log.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tap.workspace = true
tracing.workspace = true
uuid.workspace = true

malprobe-common.workspace = true
malprobe-config.workspace = true
