[package]
name = "malprobe-worker"
version.workspace = true
edition.workspace = true

[dependencies]
clamav-client = { workspace = true }
dotenvy = { workspace = true }
hex = { workspace = true }
infer = { workspace = true }
malprobe-config = { workspace = true }
malprobe-database = { workspace = true }
malprobe-vo = { workspace = true }
pgmq = { workspace = true }
reqwest = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true, features = ["serde"] }
