//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "file_status")]
pub enum FileStatus {
    #[sea_orm(string_value = "pending")]
    Pending,
    #[sea_orm(string_value = "scanning")]
    Scanning,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    Hash,
    strum :: Display,
    strum :: EnumString,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "file_verdict")]
pub enum FileVerdict {
    #[sea_orm(string_value = "clean")]
    Clean,
    #[sea_orm(string_value = "suspicious")]
    Suspicious,
    #[sea_orm(string_value = "malicious")]
    Malicious,
    #[sea_orm(string_value = "error")]
    Error,
}
